### ISSUE TITLE
Past values from influxdb showing as current state

### ISSUE THREAD

**Issue by webgps** [ayeks/bme680_to_influxdb#1]
Dear Lars,

Do you know why is chronograph and grafana shows past values picked from influxDB? In the screenshot, 45% is visible but it should be 51% regardin to the last data sent from pi. 45%was about an hour ago.

Thanks

Rudolf

![past_values](https://user-images.githubusercontent.com/44380977/50932633-7db8e600-1466-11e9-9f23-67aa9e71632e.png)

**Comment by ayeks** [comment]
Hi! My guess is that there is something wrong with the metrics calculation. 

Can you paste or screenshot me the Metrics info of the singlestat panel?

Here is my select statement:
```
SELECT last("humi") FROM /^$measurement$/ WHERE ("run" =~ /^$run$/ AND "location" = 'bedroom') AND $timeFilter GROUP BY time($__interval) fill(null)
```

**Comment by ayeks** [comment]
Close due inactivity.
