### ISSUE TITLE
senddata.py bricht mit Fehlermeldung ab

### ISSUE THREAD

**Issue by kubafromqlb** [ayeks/bme680_to_influxdb#2]
File "/home/pi/bme680/examples/bme680_to_influxdb/test_bme680", line 15, in <module>
    sensor = bme680.BME680()
  File "/usr/local/lib/python3.7/dist-packages/bme680/__init__.py", line 25, in __init__
    self.chip_id = self._get_regs(CHIP_ID_ADDR, 1)
  File "/usr/local/lib/python3.7/dist-packages/bme680/__init__.py", line 296, in _get_regs
    return self._i2c.read_byte_data(self.i2c_addr, register)
OSError: [Errno 121] Remote I/O error

BME 680 ist mit i2cdetect sichtbar
InfluxDB v. 1.6.4

Wo ist mein Fehler?

**Comment by ayeks** [comment]
Hey, I'll stick to English here.

The script is based on the bme680 python module. Check if you are able to get data by using this module. Follow the instructions here: <https://learn.pimoroni.com/tutorial/sandyj/getting-started-with-bme680-breakout>

```bash
sudo pip install bme680
curl https://get.pimoroni.com/bme680 | bash
cd /home/pi/bme680/examples
python read-all.py
```

If that is working, the `senddata.py`  script should work as well.

**Comment by kubafromqlb** [comment]
In der Datei "_init_.py " wird die Adresse 0x76 definiert.
Der BME680 verwendet 0x77
Eine Änderung in " def __init__(self, i2c_addr=I2C_ADDR_SECONDARY, i2c_device=None):"
hat das Problem gelöst.
Danke
