### ISSUE TITLE
Issue with timezones

### ISSUE THREAD

**Issue by eamkrc** [ayeks/bme680_to_influxdb#4]
First time posting, so sorry for bad form

Awesome script, I'm using Europe/Tallinn timezone which caused me problems with data being 3 hours in the future, influx and grafana seemed to be configured properly. Finally had to change the code in your script

```
line 129 old
iso = time.ctime()
my fix
iso = datetime.datetime.utcnow().strftime('%a %b %d %H:%M:%S %Y')
```

Maybe just a me problem but thought I would share if anyone else has similar issues with dashboards in grafana

**Comment by ayeks** [comment]
Hey thanks for the remark! You are more than welcome to push a pull request to that line. I am currently unable to test the script with the changes.

**Comment by padalev** [comment]
Same issue here.
Pushed a pull request that should solve the problem.

**Comment by ayeks** [comment]
Thanks a lot for the pull request. It is merged know.
